language: rust
os:
  - linux
  - osx
  - windows
rust:
  - stable
  - beta
  - nightly
script:
  - cargo run --bin run_all_tests
# Also run the tests on a non-x86, big-endian system.
matrix:
  include:
    - name: "mips64"
      os: linux
      rust: stable
      install:
        - cargo install cross
      script:
        - cross test --target mips64-unknown-linux-gnuabi64 --all-features --manifest-path=blake2b/Cargo.toml
        - cross test --target mips64-unknown-linux-gnuabi64 --all-features --manifest-path=blake2s/Cargo.toml
