language: rust
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly
script:
  # With std and blake2bp.
  - cargo test -vv --all-features
  # Without std.
  - cargo test -vv --no-default-features
  # Test the b2sum sub-crate.
  - (cd b2sum && cargo test -vv)
