[package]
name = "blake2b_simd"
version = "0.1.0"
authors = ["Jack O'Connor <oconnor663@gmail.com>"]

[dependencies]
arrayref = "0.3.4"
arrayvec = { version = "0.4.7", default-features = false, features = ["use_union"] }
byteorder = { version = "1.2.4", default-features = false }
constant_time_eq = "0.1.3"

[dev-dependencies]
hex = "0.3.2"

[features]
default = ["std"]
std = []
