[package]
name = "blake2b_simd"
version = "0.1.0"
authors = ["Jack O'Connor <oconnor663@gmail.com>"]

[dependencies]
byteorder = { version = "1.2.4", default-features = false }

[dev-dependencies]
hex = "0.3.2"
