[package]
name = "benchmark_gig"
version = "0.1.0"
authors = ["Jack O'Connor <oconnor663@gmail.com>"]
edition = "2018"

[dependencies]
blake2b_simd = { path = "../.." }
rand = "0.6.5"
openssl = "0.10.20"
libsodium-ffi = "0.1.16"
